name: "Deploy development"

on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."


    tests:
        runs-on: ubuntu-latest
        steps:
        - run: echo "Execution contract-test" 