name: "Deploy development"

on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Build application
            - run: echo "Executing build app"



    tests:
        runs-on: ubuntu-latest
        steps:
            - name: Setup newman
            - run: echo "Setup newman"

            - name: Execute contract-test
            - run: echo "Execution contract-test"

