name: "Deploy development"

on: [push]
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 23

            - name: Checking version node-npm
              run: |
                node -v
                npm -v

            - name: Install newman
              run: |
                npm install -g newman
                newman -v

            - name: Execute test
              run: |
                newman run collections/poc-contract-test.postman_collection.json